### ISSUE TITLE
Repo list contains archived repos with no differentiation

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/gallery-dashboard#4]
The list of repositories shown on the homepage includes those repositories that are archived, but has no indication of that status.
It would be useful to have them marked as Archived somehow.

**Comment by amis92** [comment]
Fixed in 526e3256c6d85f36c87df407f64f4b31a63adeaf - checkbox added, archived repos are hidden by default, and when shown, have a badge "Archived" by their name.
